#!/bin/bash

echo "npm 퍼블리시 가이드"
echo "=================="
echo ""
echo "1. 먼저 npm에 로그인하세요:"
echo "   npm login"
echo ""
echo "   Username: blizard4479"
echo "   Password: (비밀번호 입력)"
echo "   Email: donghyunkim.me@gmail.com"
echo ""
echo "2. 로그인 후 이 명령어로 퍼블리시:"
echo "   npm publish"
echo ""
echo "3. 성공하면 다음에서 확인 가능:"
echo "   https://www.npmjs.com/package/gemini-srt-translator"
echo ""
echo "주의: 패키지 이름이 이미 사용 중일 수 있습니다."
echo "그런 경우 package.json의 name을 변경해야 합니다."